vich_uploader:
    db_driver: orm

    mappings:
        image_plat:
            uri_prefix: /img/plat
            upload_destination: '%kernel.project_dir%/public/img/plat'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
